create schema g4sadmin;



CREATE TABLE RATES_BY_COUNTRY(

				ID_COUNTRY INT NOT NULL,
				COUNTRY_NAME    VARCHAR(100),
				LAND_MIN_STD 	DOUBLE,
				LAND_MAX_STD 	DOUBLE,
				LAND_MIN_ADD5 	DOUBLE,
				LAND_MAX_ADD5 	DOUBLE,
				LAND_MIN_ADD10 	DOUBLE,
				LAND_MAX_ADD10 	DOUBLE,
				LAND_MIN_GF1 	DOUBLE,
				LAND_MAX_GF1 	DOUBLE,
				LAND_MIN_GF2 	DOUBLE,
				LAND_MAX_GF2 	DOUBLE,
				MOBI_MIN_STD 	DOUBLE,
				MOBI_MAX_STD 	DOUBLE,
				MOBI_MIN_ADD5 	DOUBLE,
				MOBI_MAX_ADD5 	DOUBLE,
				MOBI_MIN_ADD10 	DOUBLE,
				MOBI_MAX_ADD10	DOUBLE,
				MOBI_MIN_GF1 	DOUBLE,
				MOBI_MAX_GF1 	DOUBLE,
				MOBI_MIN_GF2 	DOUBLE,
				MOBI_MAX_GF2 	DOUBLE,


				PRIMARY KEY (ID_COUNTRY)
);




CREATE TABLE AREA_CODES(

			ID_COUNTRY INT NOT NULL,
			COUNTRY_NAME    	VARCHAR(100),
			AREA_NAME 		VARCHAR(60),
			SUBGPU 			VARCHAR(5),
			CITY_SERVICE_NAME 	VARCHAR(100),
			MOBILE_NETWORK		VARCHAR(100),
			SPECIFIC_STD		DOUBLE,
			SPECIFIC_ADD5		DOUBLE,
			SPECIFIC_ADD10		DOUBLE,
			SPECIFIC_GF1		DOUBLE,
			SPECIFIC_GF2		DOUBLE,
			SPECIFIC_TYPE		VARCHAR(15),
			PHONE_NUMBER		VARCHAR(40),
			TWO_HUNDRED_MOBILE		INTEGER,

			FOREIGN KEY (ID_COUNTRY)
    			REFERENCES RATES_BY_COUNTRY(ID_COUNTRY)
			
);
